SET IDENTITY_INSERT [dbo].[Color] ON
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (1, N'Blue')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (2, N'Green')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (3, N'Silver')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (4, N'Red')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (5, N'Black')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (6, N'Sky Blue')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (7, N'Light Gold')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (8, N'Cloud White')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (9, N'Space Black')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (10, N'Mist Blue')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (11, N'Sage')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (12, N'White')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (13, N'Lavender')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (14, N'Deep Blue')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (15, N'Cosmic Orange')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (16, N'Midnight')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (17, N'Startlight')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (18, N'Orange')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (19, N'Yellow')
INSERT INTO [dbo].[Color] ([ColorID], [ColorName]) VALUES (20, N'Purple')
SET IDENTITY_INSERT [dbo].[Color] OFF
