//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ImageID { get; set; }
        public int ProID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
    }
}
